// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNY3hqqJTDl8QPV4XFy25f8mdoaMECaPY',
    appId: '1:983678184026:web:b6584c237752ce42a7c663',
    messagingSenderId: '983678184026',
    projectId: 'huit-student-request-app',
    authDomain: 'huit-student-request-app.firebaseapp.com',
    storageBucket: 'huit-student-request-app.firebasestorage.app',
    measurementId: 'G-8C220WG3SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_KDE77OY0t_D5lNdJoEnvmcGthkRH90',
    appId: '1:983678184026:android:a962d2ab305a5227a7c663',
    messagingSenderId: '983678184026',
    projectId: 'huit-student-request-app',
    storageBucket: 'huit-student-request-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSaD3xZwY2vu-AtQoLeLh_y6flq7YnG8o',
    appId: '1:983678184026:ios:479e8f9ed538dd49a7c663',
    messagingSenderId: '983678184026',
    projectId: 'huit-student-request-app',
    storageBucket: 'huit-student-request-app.firebasestorage.app',
    iosBundleId: 'com.example.huitStudentRequestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSaD3xZwY2vu-AtQoLeLh_y6flq7YnG8o',
    appId: '1:983678184026:ios:479e8f9ed538dd49a7c663',
    messagingSenderId: '983678184026',
    projectId: 'huit-student-request-app',
    storageBucket: 'huit-student-request-app.firebasestorage.app',
    iosBundleId: 'com.example.huitStudentRequestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNY3hqqJTDl8QPV4XFy25f8mdoaMECaPY',
    appId: '1:983678184026:web:f7e862803b7a8409a7c663',
    messagingSenderId: '983678184026',
    projectId: 'huit-student-request-app',
    authDomain: 'huit-student-request-app.firebaseapp.com',
    storageBucket: 'huit-student-request-app.firebasestorage.app',
    measurementId: 'G-Y86Y2YGDWM',
  );
}
